# Set variables for programs to be called

$terminal = kitty
$fileManager = thunar
$menu = walker 
$statusBar = waybar
$hyprcolor = hyprpicker -a -f rgb
$editHyprConf = nvim ~./config/hypr/hyprland.conf 

#################
### AUTOSTART ###
#################

# Or execute your favorite apps at launch like this:
exec-once = $terminal
exec-once = $statusBar 
exec-once = systemctl --user start hyprpolkitagent.service
exec-once = ~/HyprTile/start-launcher.sh & disown
exec-once = systemctl --user start elephant.service & walker --gapplication.service & disown
exec-once = nm-applet &
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprsunset
exec-once = hyprpaper
