general {
    gaps_in = 3
    gaps_out = 8

    border_size = 2
  
  # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(c63d7cff) rgba(9eced4ff) 45deg
    col.inactive_border = rgba(BD9FDFff)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle

}
