#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 2
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}
device {
    name = steelseries-steelseries-aerox-9-wireless-3
    scroll_button = 274
    scroll_button_lock = true 
  #  sensitivity = -0.5
}

device {
    name = steelseries-steelseries-aerox-9-wireless-2
    scroll_button = 274
    scroll_button_lock = true 
   # sensitivity = -0.5
}

device {
    name = steelseries-steelseries-aerox-9-wireless-1
    scroll_button = 274
    scroll_button_lock = true 
    #sensitivity = -0.5
}

device {
    name = steelseries-steelseries-aerox-9-wireless
    scroll_button = 274
    scroll_button_lock = true 
    #sensitivity = -0.5
}
